import pygame
from math import sin, cos, pi, tan, degrees, sqrt, atan2
from map import map_visualized

# video settings
WIDTH, HEIGHT = 1200, 800
HALF_WIDTH, HALF_HEIGHT = WIDTH // 2, HEIGHT // 2
OPTIMISED_HEIGHT = HEIGHT * 5
DOUBLE_HEIGHT = HEIGHT * 2
CELL = 100
FRAMES_PER_SECOND = 360

# audio settings
MUSIC = [
    1
]
# LEVEL_MUSIC = 'music/Daniel Deluxe - Infiltrator.mp3'
LEVEL_MUSIC = 'music/Daniel Deluxe - Truth to Power.mp3'

# palette
RED = (255, 0, 0)
GREEN = (0, 255, 0)
BLUE = (0, 0, 255)

MINI_MAP_COLOR = (47, 79, 79)
BLUE_SKY_COLOR = (0, 191, 255)
GROUND_COLOR = (100, 100, 100)

BLACK = (0, 0, 0)  # lives matter
WHITE = (255, 255, 255)

# FPS settings
PLAYER_POSITION = (CELL * 8.5, CELL * 1.5)
PLAYER_SPEED = 3
PLAYER_ANGLE = 1.55
PLAYER_ROTATE_SPEED = 0.02

# ray cast settings
MAX_DEPTH = 1000
FIELD_OF_VIEW = pi / 3
HALF_FIELD_OF_VIEW = FIELD_OF_VIEW / 2
NUMBER_OF_RAYS = 300
DELTA_OF_ANGLE = FIELD_OF_VIEW / NUMBER_OF_RAYS
DISTANCE = NUMBER_OF_RAYS / (2 * tan(HALF_FIELD_OF_VIEW))
COEFFICIENT = 3 * NUMBER_OF_RAYS * CELL
SCALE = WIDTH // NUMBER_OF_RAYS

# mini map settings
MINI_MAP_SCALE = 5
MINI_MAP_RES = (WIDTH // MINI_MAP_SCALE, HEIGHT // MINI_MAP_SCALE)
MAP_SCALE = 2 * MINI_MAP_SCALE
MAP_CELL = CELL // MAP_SCALE
MAP_POSITION = (0, HEIGHT - HEIGHT // MINI_MAP_SCALE)

# texture settings
TEXTURE_WIDTH = 128
TEXTURE_HEIGHT = 128
TEXTURE_SCALE = TEXTURE_WIDTH // CELL
HALF_TEXTURE_HEIGHT = TEXTURE_HEIGHT // 2

# sprite settings
DOUBLE_PI = pi * 2
CENTRAL_RAY = NUMBER_OF_RAYS // 2 - 1
ADDITIONAL_RAYS = 100
ADDITIONAL_RAYS_RANGE = NUMBER_OF_RAYS - 1 + 2 * ADDITIONAL_RAYS
